title: Michael Ruby # your name (or website title) here
logo: "/images/LinkedInPicture.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate from University of British Columbia Vancouver with a Bachelor's Degree in Cognitive Systems
  <br><br>
  Interested in all things data science.
  <br><br>
  <a href="https://www.linkedin.com/in/michael-ruby13/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
